version: '3'

services:
    server1:
        build: .
        image: devops787/docker-nginx-proxy
        restart: always
        environment:
            SERVER_ID: 1

    server2:
        build: .
        image: devops787/docker-nginx-proxy
        restart: always
        environment:
            SERVER_ID: 2

    server3:
        build: .
        image: devops787/docker-nginx-proxy
        restart: always
        environment:
            SERVER_ID: 3

    nginx:
        image: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
